# Use an official Node.js runtime as a parent image
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .
ENV DATABASE_URL="postgresql://zada-lms:zada-lms@192.168.1.141:5432/zada-lms?schema=public"

# Generate Prisma client
RUN npx prisma generate

# Build the Next.js application
RUN npm run build

# Reduce the image size by using a minimal base image
# FROM node:20-alpine AS runner

# # Set environment variables
# ENV NODE_ENV=production

# # Set the working directory
# WORKDIR /app

# # Copy the built application from the builder stage
# COPY --from=builder /app ./

# # Expose the port that the app runs on
# EXPOSE 3000

# # Command to run the application
# CMD ["npm"]