---
version: "3"
services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: "inventify"
      POSTGRES_DB: "inventify"
      POSTGRES_PASSWORD: "inventify"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data/pgdata
      - ./:/docker-entrypoint-initdb.d/
